# -*- coding: utf-8 -*-
"""SatuTani_Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R85IOy4yt10svieGd7ye_4jbucGY89C7

# 🌾 SatuTani — Chatbot Pertanian Cerdas (LCEL Edition)
## AI-Powered Agricultural Recommendation System
> LangChain LCEL | ReAct Agent | 6 @tool | BMKG Real-time | Google Colab Ready

---

### Arsitektur Sistem
```
Petani Tanya
     │
     ▼
┌────────────────────────────────────────┐
│   ReAct Agent (LCEL Pipeline)          │
│   prompt | llm.bind_tools | parser     │
└────────────────────────────────────────┘
     │
     ├── 🌤️  get_cuaca_realtime       (BMKG API)
     ├── 🌱  rekomendasikan_komoditas  (Gaussian scoring)
     ├── 📅  jadwal_tanam_terbaik     (proyeksi 8 minggu)
     ├── 🐛  info_hama_penyakit       (RAG → ChromaDB)
     ├── 💰  estimasi_hasil_panen     (kalkulasi finansial)
     └── 📊  cek_harga_pasar          (demand SatuTani)
```

## 📦 Cell 1 — Install Dependencies
"""

# !pip install langchain==0.2.16 \
# langchain-core==0.2.38 \
# langchain-openai==0.1.23 \
# langchain-groq==0.1.9 \
# langchain-huggingface==0.0.3 \
# langchain-chroma==0.1.2 \
# chromadb sentence-transformers -q

"""## ⚙️ Cell 2 — Import & Konfigurasi"""

# !pip uninstall -y numpy pandas
# !pip install numpy==1.26.4 pandas==2.2.2 -q

import os
# os.kill(os.getpid(), 9)

# ── Basic Python ────────────────────────────────────────────────────────────
import os
import json
import math
import time
import requests


import pandas as pd
import numpy as np
from datetime import datetime, timedelta

from langchain_core.tools import tool
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.documents import Document

# ── LLM (Groq) ──────────────────────────────────────────────────────────────
from langchain_groq import ChatGroq

# ── Vector Store & Embeddings ───────────────────────────────────────────────
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter

# ── (Opsional) Debug versi ──────────────────────────────────────────────────
import langchain
import langchain_core
import langchain_groq

# ── API Key ──────────────────────────────────────────────────────────────────
import os
os.environ["GROQ_API_KEY"]  = "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"

# ── Konfigurasi Wilayah ──────────────────────────────────────────────────────
WILAYAH_TARGET = [
    {"nama":"Lembang",      "adm4":"32.17.06.2003","lat":-6.8100,"lon":107.6100},
    {"nama":"Bandung Kota", "adm4":"32.73.04.1001","lat":-6.9147,"lon":107.6098},
    {"nama":"Bekasi",       "adm4":"32.16.01.2001","lat":-6.2383,"lon":106.9756},
    {"nama":"Tasikmalaya",  "adm4":"32.78.01.1001","lat":-7.3274,"lon":108.2207},
    {"nama":"Cianjur",      "adm4":"32.03.01.2001","lat":-6.8200,"lon":107.1400},
    {"nama":"Sukabumi",     "adm4":"32.02.32.2003","lat":-6.9200,"lon":106.9300},
]
WILAYAH_DICT  = {w["nama"]: w for w in WILAYAH_TARGET}
WILAYAH_NAMES = [w["nama"] for w in WILAYAH_TARGET]
MINGGU_KE_DEPAN = 8

print(f"\n📍 Wilayah: {', '.join(WILAYAH_NAMES)}")
print("✅ Konfigurasi siap!")

"""## 🧠 Cell 3 — Knowledge Base Komoditas (FAO + Kementan + ecommerce + google + ai)"""

KNOWLEDGE_BASE = [
    # ── Hortikultura ─────────────────────────────────────────────────────────
    {"commodity":"cabai",         "nama_lokal":"Cabai Merah",   "temp_min":18,"temp_max":27,"rain_min":600, "rain_max":1250,"humidity_min":60,"humidity_max":80,"growing_days":120,"yield_ton_per_ha":15,"harga_base":35000},
    {"commodity":"cabai_rawit",   "nama_lokal":"Cabai Rawit",   "temp_min":20,"temp_max":30,"rain_min":500, "rain_max":1200,"humidity_min":60,"humidity_max":80,"growing_days":110,"yield_ton_per_ha":10,"harga_base":40000},
    {"commodity":"tomat",         "nama_lokal":"Tomat",         "temp_min":18,"temp_max":25,"rain_min":400, "rain_max":800, "humidity_min":60,"humidity_max":80,"growing_days":100,"yield_ton_per_ha":20,"harga_base":8000},
    {"commodity":"terong",        "nama_lokal":"Terong Ungu",   "temp_min":22,"temp_max":30,"rain_min":500, "rain_max":1000,"humidity_min":65,"humidity_max":80,"growing_days":90, "yield_ton_per_ha":25,"harga_base":6000},
    {"commodity":"timun",         "nama_lokal":"Mentimun",      "temp_min":21,"temp_max":30,"rain_min":200, "rain_max":400, "humidity_min":60,"humidity_max":80,"growing_days":45, "yield_ton_per_ha":20,"harga_base":4500},
    {"commodity":"buncis",        "nama_lokal":"Buncis",        "temp_min":16,"temp_max":24,"rain_min":300, "rain_max":500, "humidity_min":60,"humidity_max":75,"growing_days":60, "yield_ton_per_ha":12,"harga_base":7000},
    {"commodity":"kacang_panjang","nama_lokal":"Kacang Panjang","temp_min":24,"temp_max":32,"rain_min":500, "rain_max":1000,"humidity_min":60,"humidity_max":80,"growing_days":60, "yield_ton_per_ha":10,"harga_base":7000},
    # ── Sayuran daun ─────────────────────────────────────────────────────────
    {"commodity":"kangkung",      "nama_lokal":"Kangkung",      "temp_min":25,"temp_max":30,"rain_min":500, "rain_max":900, "humidity_min":75,"humidity_max":85,"growing_days":27, "yield_ton_per_ha":8, "harga_base":3000},
    {"commodity":"bayam",         "nama_lokal":"Bayam",         "temp_min":18,"temp_max":25,"rain_min":100, "rain_max":200, "humidity_min":60,"humidity_max":75,"growing_days":30, "yield_ton_per_ha":6, "harga_base":4000},
    {"commodity":"sawi",          "nama_lokal":"Sawi Hijau",    "temp_min":20,"temp_max":28,"rain_min":200, "rain_max":400, "humidity_min":60,"humidity_max":80,"growing_days":40, "yield_ton_per_ha":10,"harga_base":4000},
    {"commodity":"selada",        "nama_lokal":"Selada",        "temp_min":15,"temp_max":20,"rain_min":250, "rain_max":500, "humidity_min":60,"humidity_max":80,"growing_days":45, "yield_ton_per_ha":15,"harga_base":8000},
    # ── Umbi ─────────────────────────────────────────────────────────────────
    {"commodity":"wortel",        "nama_lokal":"Wortel",        "temp_min":15,"temp_max":22,"rain_min":200, "rain_max":400, "humidity_min":60,"humidity_max":75,"growing_days":100,"yield_ton_per_ha":25,"harga_base":6000},
    {"commodity":"kentang",       "nama_lokal":"Kentang",       "temp_min":15,"temp_max":20,"rain_min":500, "rain_max":700, "humidity_min":60,"humidity_max":80,"growing_days":100,"yield_ton_per_ha":20,"harga_base":10000},
    {"commodity":"bawang_merah",  "nama_lokal":"Bawang Merah",  "temp_min":18,"temp_max":25,"rain_min":350, "rain_max":550, "humidity_min":50,"humidity_max":70,"growing_days":90, "yield_ton_per_ha":10,"harga_base":25000},
    # ── Pangan ───────────────────────────────────────────────────────────────
    {"commodity":"jagung",        "nama_lokal":"Jagung",        "temp_min":21,"temp_max":30,"rain_min":500, "rain_max":1200,"humidity_min":50,"humidity_max":80,"growing_days":75, "yield_ton_per_ha":12,"harga_base":4000},
    {"commodity":"padi",          "nama_lokal":"Padi Sawah",    "temp_min":22,"temp_max":30,"rain_min":1200,"rain_max":2000,"humidity_min":70,"humidity_max":90,"growing_days":120,"yield_ton_per_ha":6, "harga_base":5000},
    # ── Buah ─────────────────────────────────────────────────────────────────
    {"commodity":"stroberi",      "nama_lokal":"Stroberi",      "temp_min":14,"temp_max":24,"rain_min":600, "rain_max":1200,"humidity_min":70,"humidity_max":85,"growing_days":90, "yield_ton_per_ha":15,"harga_base":45000},
    {"commodity":"semangka",      "nama_lokal":"Semangka",      "temp_min":22,"temp_max":32,"rain_min":300, "rain_max":600, "humidity_min":60,"humidity_max":80,"growing_days":80, "yield_ton_per_ha":20,"harga_base":5000},
    {"commodity":"melon",         "nama_lokal":"Melon",         "temp_min":20,"temp_max":30,"rain_min":200, "rain_max":400, "humidity_min":60,"humidity_max":80,"growing_days":75, "yield_ton_per_ha":18,"harga_base":9000},
    {"commodity":"pisang",        "nama_lokal":"Pisang",        "temp_min":25,"temp_max":35,"rain_min":1200,"rain_max":2500,"humidity_min":70,"humidity_max":90,"growing_days":300,"yield_ton_per_ha":30,"harga_base":3000},
]

KB_DICT = {k["commodity"]: k for k in KNOWLEDGE_BASE}
df_kb   = pd.DataFrame(KNOWLEDGE_BASE)
KOMODITAS_UTAMA = [k["commodity"] for k in KNOWLEDGE_BASE]

print(f"✅ Knowledge Base: {len(KNOWLEDGE_BASE)} komoditas")
df_kb[["commodity","nama_lokal","temp_min","temp_max","rain_min","rain_max","growing_days","yield_ton_per_ha"]]

"""## 🌤️ Cell 4 — Dataset Cuaca BMKG (Scraping + Fallback Klimatologi)"""

IKLIM_WILAYAH = {
    "Lembang":      {"suhu":(16,21),"hujan":(15,40), "lembab":(80,93)},
    "Bandung Kota": {"suhu":(19,26),"hujan":(8, 28), "lembab":(68,84)},
    "Bekasi":       {"suhu":(27,35),"hujan":(3, 18), "lembab":(55,72)},
    "Tasikmalaya":  {"suhu":(20,28),"hujan":(10,32), "lembab":(70,86)},
    "Cianjur":      {"suhu":(18,27),"hujan":(8, 28), "lembab":(72,88)},
    "Sukabumi":     {"suhu":(19,28),"hujan":(10,30), "lembab":(70,87)},
}

def ambil_cuaca_bmkg(adm4: str, nama: str) -> list:
    url = f"https://api.bmkg.go.id/publik/prakiraan-cuaca?adm4={adm4}"
    try:
        r = requests.get(url, headers={"User-Agent":"SatuTani/2.0"}, timeout=15)
        r.raise_for_status()
        cuaca_list = r.json().get("data",[{}])[0].get("cuaca",[])
        semua = []
        for g in cuaca_list:
            semua.extend(g) if isinstance(g, list) else semua.append(g)
        df_raw = pd.DataFrame(semua)
        if df_raw.empty: return []
        df_raw["datetime"] = pd.to_datetime(df_raw["local_datetime"], errors="coerce")
        df_raw["week_num"] = ((df_raw["datetime"] - datetime.now()) / np.timedelta64(1,"W")).astype(int) + 1
        df_raw = df_raw[df_raw["week_num"].between(1, MINGGU_KE_DEPAN)]
        hasil = []
        for week, grp in df_raw.groupby("week_num"):
            hasil.append({
                "region":r_name if (r_name:=nama) else nama,
                "adm4":adm4, "week":int(week),
                "week_start":(datetime.now()+timedelta(weeks=week-1)).strftime("%Y-%m-%d"),
                "temperature_avg":round(pd.to_numeric(grp.get("t",  pd.Series()), errors="coerce").mean(),1),
                "temperature_min":round(pd.to_numeric(grp.get("t",  pd.Series()), errors="coerce").min(), 1),
                "temperature_max":round(pd.to_numeric(grp.get("t",  pd.Series()), errors="coerce").max(), 1),
                "rainfall_mm":    round(pd.to_numeric(grp.get("tp", pd.Series(dtype=float)), errors="coerce").sum(),1),
                "humidity":       round(pd.to_numeric(grp.get("hu", pd.Series()), errors="coerce").mean(),1),
                "wind_speed":     round(pd.to_numeric(grp.get("ws", pd.Series()), errors="coerce").mean(),1),
                "weather_code":   grp.get("weather",pd.Series()).mode()[0] if not grp.empty else None,
                "scraped_at":     datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "source":         "BMKG_API",
            })
        return hasil
    except Exception as e:
        print(f"  ⚠️  {nama}: {e}")
        return []

def cuaca_fallback(nama: str) -> list:
    iklim = IKLIM_WILAYAH[nama]
    rows = []
    for week in range(1, MINGGU_KE_DEPAN+1):
        f = 1 - week*0.04
        rows.append({
            "region":nama, "adm4":WILAYAH_DICT[nama]["adm4"], "week":week,
            "week_start":(datetime.now()+timedelta(weeks=week-1)).strftime("%Y-%m-%d"),
            "temperature_avg":round(np.random.uniform(*iklim["suhu"])+week*0.3,1),
            "temperature_min":round(iklim["suhu"][0]-2,1),
            "temperature_max":round(iklim["suhu"][1]+2,1),
            "rainfall_mm":    round(max(3, np.random.uniform(*iklim["hujan"])*f),1),
            "humidity":       round(max(50,np.random.uniform(*iklim["lembab"])*f),1),
            "wind_speed":     round(np.random.uniform(3,12),1),
            "weather_code":   np.random.choice([0,1,2,3,60,61]),
            "scraped_at":     datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "source":         "SIMULASI_KLIMATOLOGI",
        })
    return rows

# ── Test koneksi BMKG ─────────────────────────────────────────────────────────
print("🔍 Test BMKG API...")
try:
    t = requests.get("https://api.bmkg.go.id/publik/prakiraan-cuaca?adm4=32.17.06.2003",timeout=10)
    USE_REAL_API = t.status_code == 200 and bool(t.json().get("data"))
    print(f"{'✅ BMKG OK — pakai data real' if USE_REAL_API else '⚠️  BMKG kosong — pakai fallback'}")
except Exception as e:
    USE_REAL_API = False
    print(f"❌ {e} — pakai fallback klimatologi")

# ── Scraping ──────────────────────────────────────────────────────────────────
print("\n🌤️  Scraping cuaca 6 wilayah...")
print("="*50)
semua_cuaca = []
for w in WILAYAH_TARGET:
    nama = w["nama"]
    print(f"  📡 {nama}...", end=" ")
    hasil = ambil_cuaca_bmkg(w["adm4"], nama) if USE_REAL_API else []
    if hasil:
        semua_cuaca.extend(hasil)
        print(f"✅ {len(hasil)} minggu (BMKG real)")
    else:
        fb = cuaca_fallback(nama)
        semua_cuaca.extend(fb)
        print(f"⚠️  {len(fb)} minggu (klimatologi)")
    time.sleep(0.3)

df_weather = pd.DataFrame(semua_cuaca)
print("="*50)
print(f"✅ Total: {len(df_weather)} baris | Sumber: {df_weather['source'].value_counts().to_dict()}")
df_weather.head(8)

"""## 📊 Cell 5 — Dataset Demand & Harga Pasar SatuTani"""

KOMODITAS_LIST = [k["commodity"] for k in KNOWLEDGE_BASE]  # otomatis 20
HARGA_BASE     = {k["commodity"]: k["harga_base"] for k in KNOWLEDGE_BASE}

PRICE_MODIFIER = {
    "Lembang": {
        "cabai":1.05, "cabai_rawit":1.05, "tomat":0.90, "terong":0.95,
        "timun":1.00, "buncis":0.90, "kacang_panjang":1.00,
        "kangkung":1.00, "bayam":0.95, "sawi":0.90, "selada":0.90,
        "wortel":0.90, "kentang":0.90, "bawang_merah":1.00,
        "jagung":1.00, "padi":1.00,
        "stroberi":0.85, "semangka":1.10, "melon":1.10, "pisang":1.05
    },
    "Bandung Kota": {
        "cabai":1.10, "cabai_rawit":1.10, "tomat":1.05, "terong":1.05,
        "timun":1.05, "buncis":1.00, "kacang_panjang":1.05,
        "kangkung":1.05, "bayam":1.00, "sawi":1.00, "selada":1.05,
        "wortel":1.05, "kentang":1.05, "bawang_merah":1.10,
        "jagung":1.05, "padi":1.05,
        "stroberi":1.00, "semangka":1.10, "melon":1.10, "pisang":1.05
    },
    "Bekasi": {
        "cabai":1.20, "cabai_rawit":1.20, "tomat":1.15, "terong":1.10,
        "timun":1.10, "buncis":1.10, "kacang_panjang":1.10,
        "kangkung":1.15, "bayam":1.10, "sawi":1.15, "selada":1.15,
        "wortel":1.15, "kentang":1.15, "bawang_merah":1.20,
        "jagung":1.10, "padi":1.10,
        "stroberi":1.30, "semangka":1.05, "melon":1.10, "pisang":1.10
    },
    "Tasikmalaya": {
        "cabai":0.95, "cabai_rawit":0.95, "tomat":0.95, "terong":0.90,
        "timun":0.95, "buncis":0.95, "kacang_panjang":0.90,
        "kangkung":0.95, "bayam":0.90, "sawi":0.95, "selada":1.00,
        "wortel":0.95, "kentang":1.00, "bawang_merah":0.95,
        "jagung":0.95, "padi":0.90,
        "stroberi":1.10, "semangka":1.00, "melon":1.00, "pisang":0.90
    },
    "Cianjur": {
        "cabai":0.90, "cabai_rawit":0.90, "tomat":0.85, "terong":0.90,
        "timun":0.90, "buncis":0.90, "kacang_panjang":0.90,
        "kangkung":0.90, "bayam":0.90, "sawi":0.90, "selada":0.90,
        "wortel":0.85, "kentang":0.90, "bawang_merah":0.90,
        "jagung":0.90, "padi":0.90,
        "stroberi":0.90, "semangka":0.95, "melon":0.95, "pisang":0.95
    },
    "Sukabumi": {
        "cabai":0.95, "cabai_rawit":0.95, "tomat":0.90, "terong":0.90,
        "timun":0.90, "buncis":0.90, "kacang_panjang":0.90,
        "kangkung":0.90, "bayam":0.90, "sawi":0.90, "selada":0.95,
        "wortel":0.90, "kentang":0.95, "bawang_merah":0.90,
        "jagung":0.90, "padi":0.90,
        "stroberi":0.95, "semangka":0.95, "melon":0.95, "pisang":0.90
    },
}

np.random.seed(42)
rows = []
for wilayah in WILAYAH_NAMES:
    for komoditas in KOMODITAS_LIST:
        rows.append({
            "region":             wilayah,
            "komoditas":          komoditas,
            "demand_score":       round(np.random.uniform(0.4, 1.0), 2),
            "harga_pasar_per_kg": int(HARGA_BASE[komoditas]
                                      * PRICE_MODIFIER[wilayah][komoditas]
                                      * np.random.uniform(0.90, 1.10)),
            "stok_level":         np.random.choice(["rendah","sedang","tinggi"], p=[0.25,0.50,0.25]),
            "tren_harga":         np.random.choice(["naik","stabil","turun"], p=[0.35,0.40,0.25]),
            "bulan":              datetime.now().strftime("%Y-%m"),
        })

df_demand = pd.DataFrame(rows)
df_demand.to_csv("satutani_demand_dataset.csv", index=False)

print(f"✅ Demand dataset: {len(df_demand)} baris ({len(WILAYAH_NAMES)} wilayah × {len(KOMODITAS_LIST)} komoditas)")
print(f"📁 Tersimpan: satutani_demand_dataset.csv")
df_demand.head(12)

"""## 🧮 Cell 6 — Gaussian Scoring Engine"""

def gaussian(value: float, ideal_min: float, ideal_max: float, penalty: float = 3.5) -> float:
    if ideal_min <= value <= ideal_max:
        return 1.0
    spread   = (ideal_max - ideal_min) / 2 + 1e-9
    distance = min(abs(value - ideal_min), abs(value - ideal_max))
    return round(math.exp(-penalty * (distance / spread) ** 2), 3)

def hitung_cuaca_score(row: dict, kb: dict) -> float:
    """
    Bobot FAO: Hujan 40% | Suhu 35% | Kelembaban 25%
    rainfall_mm (mm/minggu) dikonversi ke mm/tahun (×52)
    """
    rain_annual = row["rainfall_mm"] * 52
    s_temp  = gaussian(row["temperature_avg"], kb["temp_min"],     kb["temp_max"])
    s_rain  = gaussian(rain_annual,            kb["rain_min"],     kb["rain_max"])
    s_humid = gaussian(row["humidity"],        kb["humidity_min"], kb["humidity_max"])
    return round(s_rain*0.40 + s_temp*0.35 + s_humid*0.25, 3)

def fetch_cuaca_sekarang(nama_wilayah: str) -> dict:
    """Ambil data cuaca minggu 1 untuk wilayah tertentu beserta cuaca_score per komoditas."""
    mask = (df_weather["region"] == nama_wilayah) & (df_weather["week"] == 1)
    row  = df_weather[mask]
    r = row.iloc[0].to_dict() if not row.empty else {
        "region":nama_wilayah,"week":1,
        "week_start":datetime.now().strftime("%Y-%m-%d"),
        "temperature_avg":24.0,"temperature_min":20.0,"temperature_max":30.0,
        "rainfall_mm":15.0,"humidity":75.0,"wind_speed":7.0,"source":"DEFAULT",
    }
    r["scores_per_komoditas"] = {k: hitung_cuaca_score(r, KB_DICT[k]) for k in KOMODITAS_UTAMA}
    r["cuaca_score_avg"] = round(np.mean(list(r["scores_per_komoditas"].values())), 3)
    return r

# Quick test
c = fetch_cuaca_sekarang("Lembang")
print(f"✅ Gaussian Scoring Engine siap!")
print(f"   Test Lembang: suhu={c['temperature_avg']}°C | hujan={c['rainfall_mm']}mm | lembab={c['humidity']}%")
print(f"   cuaca_score_avg: {c['cuaca_score_avg']}")

"""## 📚 Cell 7 — Vector Store RAG (ChromaDB + sentence-transformers)"""

DOKUMEN_HAMA = [
    """Hama Thrips (Thrips parvispinus) pada Cabai:
Thrips menyerang dengan mengisap cairan daun muda. Gejala: daun menggulung ke atas, berwarna perak/coklat.
Serangan parah terjadi saat musim kemarau kelembaban <60%.
Pengendalian: spinosad atau abamectin tiap 7 hari. Pencegahan: mulsa perak.""",

    """Penyakit Antraknosa (Colletotrichum) pada Cabai:
Bercak cekung coklat kehitaman pada buah. Faktor risiko: hujan tinggi, kelembaban >80%.
Pengendalian: fungisida mankozeb, sanitasi kebun, panen serempak.""",

    """Hama Ulat Buah Tomat (Helicoverpa armigera):
Larva menggerek buah dari luar. Puncak serangan: kemarau.
Pengendalian: Bacillus thuringiensis (Bt), klorantraniliprol, rotasi insektisida.""",

    """Penyakit Layu Fusarium Tomat (Fusarium oxysporum):
Layu mendadak, daun menguning dari bawah. Menyebar lewat air dan alat.
Pengendalian: varietas tahan, solarisasi tanah, trichoderma.""",

    """Hama Penggerek Batang Jagung (Ostrinia furnacalis):
Larva menggerek batang, daun tengah mengering (dead heart). Produksi turun 20-80%.
Pengendalian: granular karbofuran di pucuk, atau Bt spray saat telur menetas.""",

    """Penyakit Bulai Jagung (Peronosclerospora maydis):
Daun bergaris kuning-putih, tanaman kerdil. Sangat menular saat kelembaban >90%.
Pengendalian: seed treatment metalaxyl, semprot mankozeb tiap 7 hari.""",

    """Hama Musim Hujan yang Perlu Diwaspadai:
1. Siput Telanjang: menyerang sayuran daun malam hari. Atasi: bait moluskisida metaldehid.
2. Lalat Buah (Bactrocera): serang cabai, tomat, melon. Atasi: perangkap metil eugenol.
3. Ulat Grayak (Spodoptera): menyerang jagung dan sayuran. Atasi: Bt spray, klorantraniliprol.""",

    """Budidaya Stroberi Dataran Tinggi (Lembang, Cianjur):
Suhu ideal 15-22°C. Media: tanah:kompos:sekam = 1:1:1, pH 5.5-6.5.
Jarak tanam 30x30cm, mulsa plastik wajib. Panen 90-120 hari, tiap 2-3 hari.""",

    """Teknik Pemupukan Organik Sayuran:
Pupuk kandang 20-30 ton/ha, 2 minggu sebelum tanam. Kompos 10-15 ton/ha.
Biofertilizer: Rhizobium untuk kacang-kacangan, Mycorrhiza untuk cabai/tomat.
MOL (Mikroorganisme Lokal) dari cucian beras, spray 2x seminggu.""",

    """Jadwal PHT (Pengendalian Hama Terpadu) Musim Hujan:
Minggu 1-2: cek siput, ulat tanah, pasang mulsa plastik.
Minggu 3-4: monitoring lalat buah, semprot fungisida preventif jika hujan >3 hari berturut.
Minggu 5-8: pengendalian antraknosa dan busuk buah, panen segera saat matang.""",
]

print("🔄 Membuat ChromaDB vector store...")
splitter  = RecursiveCharacterTextSplitter(chunk_size=512, chunk_overlap=64)
docs = []
for i, teks in enumerate(DOKUMEN_HAMA):
    for j, chunk in enumerate(splitter.split_text(teks)):
        docs.append(Document(page_content=chunk, metadata={"doc_id":i,"chunk":j}))

print(f"   {len(docs)} chunks dari {len(DOKUMEN_HAMA)} dokumen")

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    model_kwargs={"device":"cpu"},
)

vectorstore = Chroma.from_documents(docs, embeddings, collection_name="satutani_hama")
retriever   = vectorstore.as_retriever(
    search_type="similarity_score_threshold",
    search_kwargs={"k":4,"score_threshold":0.2},
)
print("✅ ChromaDB + embeddings siap!")

"""## 🛠️ Cell 8 — 6 LangChain Tools (`@tool` decorator)"""

# ════════════════════════════════════════════════════════════════════════════
# TOOL 1 — get_cuaca_realtime
# ════════════════════════════════════════════════════════════════════════════
@tool
def get_cuaca_realtime(wilayah: str) -> str:
    """Ambil data cuaca real-time dari BMKG untuk wilayah tertentu.
    Menghasilkan suhu, curah hujan, kelembaban, dan cuaca_score per komoditas.
    Gunakan tool ini PERTAMA sebelum tool lainnya.
    Input: nama wilayah, contoh 'Lembang' atau 'Bekasi'."""
    wilayah = wilayah.strip().title()
    if wilayah not in WILAYAH_DICT:
        match = [w for w in WILAYAH_NAMES if wilayah.lower() in w.lower()]
        wilayah = match[0] if match else WILAYAH_NAMES[0]

    c = fetch_cuaca_sekarang(wilayah)
    out  = f"=== CUACA {wilayah.upper()} ({c['week_start']}) ===\n"
    out += f"Suhu   : {c['temperature_avg']}°C (min {c['temperature_min']} / max {c['temperature_max']})\n"
    out += f"Hujan  : {c['rainfall_mm']} mm/minggu (~{c['rainfall_mm']*52:.0f} mm/tahun)\n"
    out += f"Lembab : {c['humidity']}%  |  Angin: {c.get('wind_speed','?')} km/jam\n"
    out += f"Sumber : {c['source']}\n\ncuaca_score per komoditas:\n"
    for k, v in sorted(c['scores_per_komoditas'].items(), key=lambda x: -x[1]):
        bar   = "█" * int(v*10)
        emoji = "✅" if v >= 0.7 else "⚠️" if v >= 0.45 else "❌"
        out  += f"  {k:<20} {bar:<10} {v} {emoji}\n"
    return out.strip()


# ════════════════════════════════════════════════════════════════════════════
# TOOL 2 — rekomendasikan_komoditas
# ════════════════════════════════════════════════════════════════════════════
@tool
def rekomendasikan_komoditas(wilayah: str) -> str:
    """Rekomendasikan 10 komoditas diurutkan berdasarkan kesesuaian cuaca
    dengan syarat tumbuh optimal menggunakan Gaussian scoring.
    Input: nama wilayah, contoh 'Lembang' atau 'Tasikmalaya'."""
    wilayah = wilayah.strip().title()
    if wilayah not in WILAYAH_DICT:
        match = [w for w in WILAYAH_NAMES if wilayah.lower() in w.lower()]
        wilayah = match[0] if match else WILAYAH_NAMES[0]

    c = fetch_cuaca_sekarang(wilayah)
    mask  = (df_weather["region"] == wilayah) & (df_weather["week"] <= 4)
    df_w  = df_weather[mask]

    scores = {}
    for kom in KOMODITAS_UTAMA:
        kb = KB_DICT[kom]
        if not df_w.empty:
            scores[kom] = round(np.mean([hitung_cuaca_score(r, kb) for _, r in df_w.iterrows()]), 3)
        else:
            scores[kom] = c["scores_per_komoditas"].get(kom, 0)

    ranking = sorted(scores.items(), key=lambda x: -x[1])
    out  = f"=== REKOMENDASI KOMODITAS — {wilayah.upper()} ===\n"
    out += f"Cuaca: suhu {c['temperature_avg']}°C | hujan {c['rainfall_mm']}mm/minggu | lembab {c['humidity']}%\n\n"
    medals = ["🥇","🥈","🥉","4️⃣","5️⃣","6️⃣","7️⃣","8️⃣","9️⃣","🔟"]
    for i, (kom, skor) in enumerate(ranking[:10]):
        kb     = KB_DICT[kom]
        label  = "SANGAT COCOK" if skor>=0.75 else "COCOK" if skor>=0.55 else "CUKUP" if skor>=0.40 else "HINDARI"
        out   += f"{medals[i]} {kom.replace('_',' ').title():<20} {skor}  [{label}]\n"
        out   += f"   Suhu ideal {kb['temp_min']}–{kb['temp_max']}°C | Panen {kb['growing_days']} hari | Yield {kb['yield_ton_per_ha']} ton/ha\n"
    return out.strip()


# ════════════════════════════════════════════════════════════════════════════
# TOOL 3 — jadwal_tanam_terbaik
# ════════════════════════════════════════════════════════════════════════════
@tool
def jadwal_tanam_terbaik(input_str: str) -> str:
    """Tentukan minggu optimal tanam berdasarkan proyeksi cuaca 8 minggu ke depan.
    Input format: 'wilayah,komoditas'
    Contoh: 'Lembang,cabai' atau 'Bekasi,jagung' atau 'Cianjur,stroberi'."""
    parts     = [p.strip() for p in input_str.split(",")]
    wilayah   = parts[0].title() if parts else "Lembang"
    komoditas = parts[1].lower().replace(" ","_") if len(parts) > 1 else "jagung"
    if wilayah not in WILAYAH_DICT:
        match = [w for w in WILAYAH_NAMES if wilayah.lower() in w.lower()]
        wilayah = match[0] if match else WILAYAH_NAMES[0]
    if komoditas not in KB_DICT:
        komoditas = "jagung"

    kb   = KB_DICT[komoditas]
    df_w = df_weather[df_weather["region"] == wilayah].sort_values("week")
    minggu = [{"week":int(r["week"]),"week_start":r["week_start"],
               "score":hitung_cuaca_score(r.to_dict(),kb),
               "temp":r["temperature_avg"],"rain":r["rainfall_mm"]}
              for _,r in df_w.iterrows()]

    best = max(minggu, key=lambda x: x["score"])
    est_panen = (datetime.strptime(best["week_start"],"%Y-%m-%d")+timedelta(days=kb["growing_days"])).strftime("%Y-%m-%d")

    out  = f"=== JADWAL TANAM — {komoditas.replace('_',' ').title()} di {wilayah} ===\n"
    out += f"Lama tanam : ±{kb['growing_days']} hari\n\n"
    out += f"✅ MINGGU TERBAIK: Minggu ke-{best['week']} (mulai {best['week_start']})\n"
    out += f"   Skor: {best['score']} | Suhu: {best['temp']}°C | Hujan: {best['rain']}mm\n"
    out += f"   Estimasi panen: ~{est_panen}\n\n"
    out += "📊 Proyeksi 8 minggu ke depan:\n"
    for m in sorted(minggu, key=lambda x: x["week"]):
        bar   = "█" * int(m["score"]*10)
        emoji = "✅" if m["score"]>=0.65 else "⚠️" if m["score"]>=0.45 else "❌"
        out  += f"  Minggu {m['week']:>2} ({m['week_start']}): {bar:<10} {m['score']} {emoji}\n"
    return out.strip()


# ════════════════════════════════════════════════════════════════════════════
# TOOL 4 — info_hama_penyakit
# ════════════════════════════════════════════════════════════════════════════
@tool
def info_hama_penyakit(query: str) -> str:
    """Cari info hama, penyakit tanaman, atau teknik budidaya via RAG (ChromaDB).
    Contoh input: 'hama thrips cabai', 'penyakit layu tomat', 'pupuk organik',
    'cara budidaya stroberi', 'hama musim hujan'."""
    try:
        hasil = retriever.invoke(query)
        if not hasil:
            return (f"Tidak ada info spesifik untuk '{query}'. "
                    f"Coba: hama cabai, penyakit jagung, pupuk organik, atau hama musim hujan.")
        out = f"=== INFO: {query.upper()} ===\n({len(hasil)} referensi ditemukan)\n\n"
        for i, d in enumerate(hasil, 1):
            out += f"--- Referensi {i} ---\n{d.page_content}\n\n"
        return out.strip()
    except Exception as e:
        return f"Error retrieval: {e}"


# ════════════════════════════════════════════════════════════════════════════
# TOOL 5 — estimasi_hasil_panen
# ════════════════════════════════════════════════════════════════════════════
@tool
def estimasi_hasil_panen(input_str: str) -> str:
    """Estimasi hasil panen dan proyeksi pendapatan petani.
    Input format: 'wilayah,komoditas,luas_ha'
    Contoh: 'Lembang,cabai,0.5' atau 'Bekasi,jagung,2' atau 'Cianjur,tomat'
    Default luas lahan = 1 hektar jika tidak disebutkan."""
    parts     = [p.strip() for p in input_str.split(",")]
    wilayah   = parts[0].title() if parts else "Lembang"
    komoditas = parts[1].lower().replace(" ","_") if len(parts)>1 else "jagung"
    try:    luas_ha = float(parts[2]) if len(parts)>2 else 1.0
    except: luas_ha = 1.0

    if wilayah not in WILAYAH_DICT:
        match = [w for w in WILAYAH_NAMES if wilayah.lower() in w.lower()]
        wilayah = match[0] if match else WILAYAH_NAMES[0]
    if komoditas not in KB_DICT: komoditas = "jagung"

    kb = KB_DICT[komoditas]
    mask_d = (df_demand["region"]==wilayah) & (df_demand["komoditas"]==komoditas)
    d_row  = df_demand[mask_d]
    harga  = int(d_row["harga_pasar_per_kg"].values[0]) if not d_row.empty else kb["harga_base"]

    c       = fetch_cuaca_sekarang(wilayah)
    c_score = c["scores_per_komoditas"].get(komoditas, 0.6)
    yield_potensi   = kb["yield_ton_per_ha"] * luas_ha
    yield_realistis = round(yield_potensi * (0.7 + 0.3*c_score), 2)
    pendapatan      = int(yield_realistis * 1000 * harga)

    out  = f"=== ESTIMASI PANEN — {komoditas.replace('_',' ').title()} | {wilayah} ===\n"
    out += f"Luas lahan : {luas_ha} hektar  |  Lama tanam: ±{kb['growing_days']} hari\n"
    out += f"Cuaca score: {c_score} (koreksi yield: {(0.7+0.3*c_score):.2f}x)\n\n"
    out += f"📦 PRODUKSI:\n"
    out += f"  Potensi    : {yield_potensi:.2f} ton\n"
    out += f"  Realistis  : {yield_realistis:.2f} ton\n\n"
    out += f"💰 KEUANGAN:\n"
    out += f"  Harga pasar : Rp {harga:,}/kg\n"
    out += f"  Pendapatan  : Rp {pendapatan:,}\n"
    out += f"  Biaya (~35%): Rp {int(pendapatan*0.35):,}\n"
    out += f"  Laba bersih : Rp {int(pendapatan*0.65):,}\n"
    out += f"\n⚠️ Proyeksi. Hasil aktual dipengaruhi OPT dan praktik budidaya."
    return out.strip()


# ════════════════════════════════════════════════════════════════════════════
# TOOL 6 — cek_harga_pasar
# ════════════════════════════════════════════════════════════════════════════
@tool
def cek_harga_pasar(input_str: str) -> str:
    """Cek harga pasar terkini dan demand score dari platform SatuTani.
    Input format: 'wilayah,komoditas' atau hanya 'wilayah' untuk semua komoditas.
    Contoh: 'Lembang,cabai' atau 'Bekasi' atau 'Tasikmalaya,jagung'."""
    parts     = [p.strip() for p in input_str.split(",")]
    wilayah   = parts[0].title() if parts else "Lembang"
    komoditas = parts[1].lower().replace(" ","_") if len(parts)>1 else None
    if wilayah not in WILAYAH_DICT:
        match = [w for w in WILAYAH_NAMES if wilayah.lower() in w.lower()]
        wilayah = match[0] if match else WILAYAH_NAMES[0]

    mask = df_demand["region"] == wilayah
    if komoditas and komoditas in KB_DICT:
        mask = mask & (df_demand["komoditas"] == komoditas)
    df_h = df_demand[mask].sort_values("demand_score", ascending=False)
    if df_h.empty: return f"Data pasar tidak ditemukan untuk {wilayah}."

    out  = f"=== HARGA PASAR — {wilayah.upper()} ({df_h['bulan'].iloc[0]}) ===\n"
    out += f"{'Komoditas':<22}{'Harga/kg':>11}{'Demand':>8}{'Stok':>9}{'Tren':>9}\n"
    out += "-"*60 + "\n"
    for _, r in df_h.head(10).iterrows():
        icon = "📈" if r["tren_harga"]=="naik" else "📉" if r["tren_harga"]=="turun" else "➡️"
        out += (f"{r['komoditas'].replace('_',' ').title():<22}"
                f"Rp {r['harga_pasar_per_kg']:>7,}"
                f"{r['demand_score']:>8.2f}"
                f"{r['stok_level']:>9}"
                f"  {icon}{r['tren_harga']}\n")
    return out.strip()


# ── Registrasi ────────────────────────────────────────────────────────────────
SATUTANI_TOOLS = [
    get_cuaca_realtime,
    rekomendasikan_komoditas,
    jadwal_tanam_terbaik,
    info_hama_penyakit,
    estimasi_hasil_panen,
    cek_harga_pasar,
]
print("✅ 6 Tools siap dengan @tool decorator:")
for t in SATUTANI_TOOLS:
    print(f"   🔧 {t.name}")

"""## 🤖 Cell 9 — ReAct Agent (LangChain terbaru)"""

# ── IMPORT ────────────────────────────────────────────────────────────────
from langchain_groq import ChatGroq
from langchain.agents import create_openai_tools_agent, AgentExecutor
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

# ── LLM (GROQ) ────────────────────────────────────────────────────────────
llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.3,
    max_tokens=2048,
)

# ── PROMPT (FORMAT WAJIB AGENT) ───────────────────────────────────────────
prompt = ChatPromptTemplate.from_messages([
   ("system", """Kamu adalah SatuTani Assistant, asisten pertanian cerdas untuk petani Indonesia.

Tugas kamu:
Memberikan rekomendasi pertanian yang jelas, praktis, dan bisa langsung diterapkan.

Wilayah yang kamu layani: {wilayah_list}

ATURAN:
- Gunakan tools jika diperlukan
- WAJIB berikan jawaban final yang lengkap (jangan hanya 1 kalimat)
- Gunakan Bahasa Indonesia natural

FORMAT JAWABAN WAJIB:

🌤️ Kondisi Saat Ini:
- Ringkas cuaca (suhu, hujan, kelembaban)

🌱 Rekomendasi Utama:
- Sebutkan 1–3 komoditas terbaik
- Sertakan alasan singkat

📊 Insight Penting:
- Kenapa cocok (berdasarkan suhu, hujan, dll)

🚀 Saran Aksi:
- Kapan mulai tanam
- Tips singkat (misal mulsa, pest control, dll)

Pastikan jawaban:
- Informatif
- Tidak kosong
- Tidak terlalu singkat

"""),

    ("human", "{input}"),

    # 🔥 WAJIB untuk agent (memory langkah berpikir)
    MessagesPlaceholder(variable_name="agent_scratchpad"),
]).partial(
    wilayah_list=", ".join(WILAYAH_NAMES),
)

# ── AGENT ─────────────────────────────────────────────────────────────────
agent = create_openai_tools_agent(
    llm=llm,
    tools=SATUTANI_TOOLS,
    prompt=prompt
)

# ── EXECUTOR (ENGINE UTAMA) ───────────────────────────────────────────────
agent_executor = AgentExecutor(
    agent=agent,
    tools=SATUTANI_TOOLS,
    verbose=True,
)

# ── INFO ──────────────────────────────────────────────────────────────────
print("✅ SatuTani Agent (Groq) siap!")
print(f"   Model  : llama-3.3-70b-versatile")
print(f"   Tools  : {len(SATUTANI_TOOLS)}")
print(f"   Mode   : Agent + Tool Reasoning")

"""## 💬 Cell 10 — Test 6 Skenario Pertanyaan Petani"""

def tanya_satutani(pertanyaan: str) -> str:
    """Kirim pertanyaan ke SatuTani (LCEL) dan tampilkan jawaban."""
    print(f"\n{'='*65}")
    print(f"🧑‍🌾 PERTANYAAN: {pertanyaan}")
    print(f"{'='*65}\n")

    try:
        # 🔥 LCEL invoke (pengganti agent_executor)
        result = agent_executor.invoke({"input": pertanyaan})
        jawaban = result["output"]

        print(f"\n{'─'*65}")
        print(f"🌾 JAWABAN AKHIR SATUTANI:")
        print(f"{'─'*65}")
        print(jawaban)

        # 🔍 Optional: tampilkan tool yang dipakai
        if hasattr(result, "tool_calls") and result.tool_calls:
            print(f"\n🔧 TOOL DIGUNAKAN:")
            for t in result.tool_calls:
                print(f"   - {t['name']} | input: {t['args']}")

        return jawaban

    except Exception as e:
        print(f"❌ Error: {e}")
        return str(e)


# ─── Skenario 1: Rekomendasi komoditas ───────────────────────────────────────
print("\n" + "🌟"*25)
print("SKENARIO 1 — Rekomendasi Komoditas")

j1 = tanya_satutani(
    "Pak, saya petani di Lembang. Komoditas apa yang paling cocok "
    "ditanam bulan ini berdasarkan cuaca sekarang?"
)

# ─── Skenario 2: Jadwal tanam ────────────────────────────────────────────────
print("\n" + "📅"*25)
print("SKENARIO 2 — Jadwal Tanam Optimal")
j2 = tanya_satutani(
    "Kapan waktu terbaik untuk mulai tanam cabai di Cianjur? "
    "Tolong tunjukkan jadwal 8 minggu ke depan."
)

# ─── Skenario 3: Info hama ───────────────────────────────────────────────────
print("\n" + "🐛"*25)
print("SKENARIO 3 — Info Hama & Penyakit")
j3 = tanya_satutani(
    "Musim hujan ini hama apa yang perlu diwaspadai untuk tanaman tomat "
    "di Bandung Kota? Cara pengendaliannya bagaimana?"
)

# ─── Skenario 4: Estimasi pendapatan ─────────────────────────────────────────
print("\n" + "💰"*25)
print("SKENARIO 4 — Estimasi Hasil Panen & Pendapatan")
j4 = tanya_satutani(
    "Saya punya lahan 0.5 hektar di Bekasi, rencananya mau tanam jagung. "
    "Kira-kira bisa dapat berapa ton dan penghasilan sekitar berapa rupiah?"
)

# ─── Skenario 5: Harga pasar ─────────────────────────────────────────────────
print("\n" + "📊"*25)
print("SKENARIO 5 — Harga Pasar & Demand")
j5 = tanya_satutani(
    "Berapa harga jual semangka dan melon di Tasikmalaya sekarang? "
    "Mana yang lebih menguntungkan untuk ditanam?"
)

# ─── Skenario 6: Komprehensif multi-tool ────────────────────────────────────
print("\n" + "🎯"*25)
print("SKENARIO 6 — Rekomendasi Lengkap (Multi-Tool Chain)")
j6 = tanya_satutani(
    "Saya petani di Sukabumi dengan lahan 1 hektar. Tolong rekomendasikan: "
    "1) Komoditas apa yang paling cocok ditanam sekarang berdasarkan cuaca? "
    "2) Kapan minggu terbaik mulai tanam? "
    "3) Estimasi penghasilan yang bisa saya dapatkan?"
)

"""## 🔧 Cell 11 — Direct Tool Test (tanpa LLM, debugging)"""

print("="*60)
print("DIRECT TOOL TEST — invoke setiap tool langsung")
print("="*60)

print("\n🌤️  TOOL 1: get_cuaca_realtime")
print(get_cuaca_realtime.invoke("Lembang"))

print("\n" + "─"*50)
print("\n🌱 TOOL 2: rekomendasikan_komoditas")
print(rekomendasikan_komoditas.invoke("Lembang"))

print("\n" + "─"*50)
print("\n📅 TOOL 3: jadwal_tanam_terbaik")
print(jadwal_tanam_terbaik.invoke("Cianjur,stroberi"))

print("\n" + "─"*50)
print("\n🐛 TOOL 4: info_hama_penyakit")
print(info_hama_penyakit.invoke("hama musim hujan sayuran"))

print("\n" + "─"*50)
print("\n💰 TOOL 5: estimasi_hasil_panen")
print(estimasi_hasil_panen.invoke("Bekasi,jagung,2"))

print("\n" + "─"*50)
print("\n📊 TOOL 6: cek_harga_pasar (single)")
print(cek_harga_pasar.invoke("Tasikmalaya"))

print("\n" + "─"*50)
print("\n📊 TOOL 6: cek_harga_pasar (multi-komoditas)")
print(cek_harga_pasar.invoke("Tasikmalaya,semangka"))

"""## 📈 Cell 12 — Analisis cuaca_score Semua Wilayah × Komoditas"""

hasil_score = []
for _, crow in df_weather.iterrows():
    for kom in KOMODITAS_UTAMA:
        hasil_score.append({
            "region": crow["region"], "week": crow["week"],
            "week_start": crow["week_start"], "komoditas": kom,
            "cuaca_score": hitung_cuaca_score(crow.to_dict(), KB_DICT[kom]),
            "temp_avg": crow["temperature_avg"], "rainfall_mm": crow["rainfall_mm"],
            "humidity": crow["humidity"],
        })

df_scores = pd.DataFrame(hasil_score)
print(f"✅ Total kombinasi: {len(df_scores)} baris")
print()
print("🏆 TOP 3 Komoditas per Wilayah (rata-rata minggu 1–4):")
print("="*60)
for w in WILAYAH_NAMES:
    top = (df_scores[(df_scores["region"]==w) & (df_scores["week"]<=4)]
           .groupby("komoditas")["cuaca_score"].mean()
           .sort_values(ascending=False).head(3))
    print(f"📍 {w}")
    for i, (kom, skor) in enumerate(top.items()):
        medal = ["🥇","🥈","🥉"][i]
        bar   = "█" * int(skor*10)
        print(f"   {medal} {kom.replace('_',' ').title():<22} {bar:<10} {skor:.3f}")
    print()

"""

### 6 Tools (`@tool` decorator dari `langchain_core.tools`)
| Tool | Input | Fungsi |
|---|---|---|
| `get_cuaca_realtime` | `wilayah` | BMKG API + cuaca_score |
| `rekomendasikan_komoditas` | `wilayah` | Gaussian ranking 10 komoditas |
| `jadwal_tanam_terbaik` | `wilayah,komoditas` | Proyeksi optimal 8 minggu |
| `info_hama_penyakit` | `query teks` | RAG ChromaDB |
| `estimasi_hasil_panen` | `wilayah,komoditas,luas_ha` | Proyeksi yield & laba |
| `cek_harga_pasar` | `wilayah,komoditas` | Demand & harga SatuTani |
"""