name: Deploy to Vercel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: satutani_mobile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Copy Vercel Configuration
        run: cp vercel.json build/web/vercel.json

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd build/web
          npx vercel --prod --yes --token $VERCEL_TOKEN --name satutani-mobile --org team_JujNQWLjVABHBQTjVNzOTBhS
